### ISSUE TITLE
Curtailment Data

### ISSUE THREAD

**Issue by narlesky** [MBKEngineers/collect#35]
See Lisa Hong's Tableau visualizations for the state:

Dashboard:
https://public.tableau.com/views/DeltaWatershedCurtailmentStatusList/sheets/Dashboard1

Profile:
https://public.tableau.com/profile/api/lisa.hong6413/workbooks?count=300&index=0

Data:
https://public.tableau.com/vizql/w/DeltaWatershedCurtailmentStatusList/v/CurtailmentList/vudcsv/sessions/5303A99772154338A639DCE701319771-0:0/views/7713620505763405234_13105237686537574087?showall=true

**Comment by connor-mbk** [comment]
Since the curtailment order was rescinded, these links are now all broken. Suggest removing this page.

**Comment by narlesky** [comment]
Thanks for the update @connor-mbk .  We will close out this potential module.
