### ISSUE TITLE
BRT/ART Data

### ISSUE THREAD

**Issue by CAbrahamMBK** [MBKEngineers/collect#69]
DWR marks data as BRT or ART if it is below or above the rating table. For some instances, I think this could be useful information over reporting NA or blanks. I started some edits to add this option if you see other uses for it. I did this specifically for a System Operations project off of the San Joaquin River and Little Dry Creek. In dry years, the Chowchilla Bypass data says BRT for much of the year which tells me there isn't enough water to divert (as opposed to some other reason for a NA such as the gage was not working/under repair).

**Comment by narlesky** [comment]
Closed by #99
